spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/reduceFatFast
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id: 
          new_generator_mappings: false
        ddl-auto: create
        format_sql: true
---
        
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: d4t4b4s3sForLif3
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
    